### ISSUE TITLE
Textual descriptions of changesets is too long

### ISSUE THREAD

**Issue by emacsen** [sbagroy986/openstreetmap-website#10]
It should just be "Changeset 1000"

**Comment by emacsen** [comment]
Is this in the commit msg somewhere?

**Comment by sbagroy986** [comment]
I haven't pushed it yet. Making some small changes and pushing it in a minute.

**Comment by emacsen** [comment]
Can you only close these once the code is pushed, please? Otherwise, it's not addressed.
