### ISSUE TITLE
In admin UI, make the report prominent

### ISSUE THREAD

**Issue by emacsen** [sbagroy986/openstreetmap-website#11]
Make the report the thing that you link to in the center, make the object on the side (less prominent)

**Comment by sbagroy986** [comment]
There are a few issues with linking the details in the center to the reports. Those links are actually created by a helper and are used in a few other places. 

To link the center text to the reports and add another "Show instance" button on the side would require 2 more helpers which may not be worth it.

![](http://i.gyazo.com/e57d8754c0e283cf29062f694643dea0.png) 

I made the Show Reports button more prominent. If this doesn't work, I can add the other helpers.

**Comment by emacsen** [comment]
Looks good. We'll discuss more tomorrow.
