### ISSUE TITLE
"Other issues" sometimes get pushed down the page

### ISSUE THREAD

**Issue by tomhughes** [sbagroy986/openstreetmap-website#16]
The "other issues by this user" section sometimes seems to get pushed down below the reports section, for example http://moderation.apis.dev.openstreetmap.org/issues/1:

![screenshot from 2015-08-12 18-32-31](https://cloud.githubusercontent.com/assets/147741/9231564/b8e3d644-4120-11e5-9dbd-cff33014533d.png)

**Comment by sbagroy986** [comment]
Fixed
![](https://i.gyazo.com/b52cb8e1234d7196b9c9ddf2af72e752.png)
