### ISSUE TITLE
Layout of issue header could be improved

### ISSUE THREAD

**Issue by tomhughes** [sbagroy986/openstreetmap-website#17]
Issue headers currently look like:

![header](https://cloud.githubusercontent.com/assets/147741/9231650/2fdd5c8e-4121-11e5-90a6-2123ac193512.png)

I would prefer to reduce the amount of vertical space by merging some stuff together and making it less like a simple print of the record. I'm thinking something like:

> Open Issue #1
> Diary Entry "Sample Diary Entry"
> 2 reports | First reported: 16 July, 2015 
> Resolve | Ignore

I'd get rid of the "iconisation" of the status as well - it's not really consistent with anything else.

**Comment by sbagroy986** [comment]
Did both. I'll close this if it looks okay now.

![](https://i.gyazo.com/f1fc2992777766f5a90095d82914b160.png)

**Comment by tomhughes** [comment]
It would be nice to convert the `DiaryEntry` class name to a nicer string like "Diary Entry" which will look prettier and also be translatable. The `site.models.diary_entry` translation (and other versions) already exists for this in fact.

Other than that it looks good.

**Comment by tomhughes** [comment]
Sorry that should be `activerecord.models.diary_entry`...

**Comment by sbagroy986** [comment]
Alright, done. I'll close this issue then.

![](https://i.gyazo.com/30eb9a8089eaea79c5e1b9a1142a5fc4.png)
