### ISSUE TITLE
Layout of issue report details could be improved

### ISSUE THREAD

**Issue by tomhughes** [sbagroy986/openstreetmap-website#18]
The detail block for an issue report currently looks like:

![report](https://cloud.githubusercontent.com/assets/147741/9231797/11905000-4122-11e5-97b4-5ca6fe7c9343.png)

As with the header I think this can be improved to make it more compact vertically. Maybe something like:

> Reported as spam by user1
> on 16 July, 2015 12:34 
> 
> This message has spam for spamco

This gets rid of the whole "tag" thing which is a bit odd looking and drops a line.

**Comment by sbagroy986** [comment]
Does this look okay? I'll close it if it does.

![](https://i.gyazo.com/3bdbc70136822fee595e7648abd9353c.png)

**Comment by tomhughes** [comment]
That looks much better, yes.
