### ISSUE TITLE
Date formatting should be consistent

### ISSUE THREAD

**Issue by tomhughes** [sbagroy986/openstreetmap-website#20]
Date formatting seems to be very inconsistent. On the issue list we have "12:34 07/16/15" while the detail page shows "16 July, 2015" and "16 July, 2015 13:31".

Our normal form is to either use our `friendly_date` helper, which gives relative dates, or `l(value, :format => :friendly)` which gives "16 July 2015".

**Comment by sbagroy986** [comment]
Is showing time of day required? I thought it may be needed so I added it. 

I can just change all the date formats to 'friendly' otherwise.

**Comment by tomhughes** [comment]
Actually I think that the friendly format does include the time for timestamps (see the message inbox page for example). The example I gave was from the diaries which I think is only a date.

**Comment by sbagroy986** [comment]
Yes I realized that later sorry. I changed it to friendly everywhere.

![](https://i.gyazo.com/614480587ee699eb930d2da4c2375d90.png)
