### ISSUE TITLE
Report type selecton should be more compact

### ISSUE THREAD

**Issue by tomhughes** [sbagroy986/openstreetmap-website#21]
The report page currently has type selection that looks like this:

![type](https://cloud.githubusercontent.com/assets/147741/9232267/a6513cde-4124-11e5-9581-5193fa75a7e4.png)

I think we should either make it a dropdown, or merge all the radio buttons into a single block without the large space between them.

**Comment by sbagroy986** [comment]
Something like this?

![](https://i.gyazo.com/4af1e8f77562e702afc93ba3b827facb.png)

**Comment by tomhughes** [comment]
Well without the whitespace after the last option but yes, that is certainly better - they are alternates so should be grouped together.

**Comment by sbagroy986** [comment]
Done. If this looks okay, I'll close this for now.

![](https://i.gyazo.com/f6f8f176118e3e7e05a29fd57a87b150.png)
