### ISSUE TITLE
User should be sent back to referring page after a report

### ISSUE THREAD

**Issue by tomhughes** [sbagroy986/openstreetmap-website#22]
Currently after completing a report you seem to be sent back to the home page. I think we should send people back to wherever they came from instead.

Even better might be to do the reporting in a popup lightbox type thing so that the calling context is completely preserved, but that might be a bit of a big ask and doesn't have any precedent in our UI at present.

**Comment by sbagroy986** [comment]
Fixed the redirection.

Like you said, the popup is a little difficult. If we had a CSS/JS library like Bootstrap, we could have simply used modals.

**Comment by tomhughes** [comment]
That looks good now.
